[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "microtorch"
version = "0.1.0"
description = "Diffusion MRI Model Fitting with PyTorch"
requires-python = ">=3.9"

dependencies = [
  "torch",
  "numpy",
  "nibabel",
  "tqdm",
  "scipy",
  "matplotlib",
  "torchmetrics",
  "optuna",
  "hydra-core",
  "jupyter"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
microtorch-create-test-images = "microtorch.utils.create_all_test_images:main"

[project.optional-dependencies]
lint = ["ruff"]
test = ["pytest"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP"]

[tool.ruff.lint.per-file-ignores]
"src/microtorch/signal_models/__init__.py" = ["E402"]
"examples/*.ipynb" = ["E402"]
