import os
import ast

def extract_callables(filepath):
    """Get all top-level functions and classes from a Python file."""
    with open(filepath, "r", encoding="utf-8") as f:
        tree = ast.parse(f.read())
    return [node.name for node in tree.body if isinstance(node, (ast.FunctionDef, ast.ClassDef))]

def populate_init_for_dir(directory):
    init_path = os.path.join(directory, "__init__.py")
    lines = ["# Auto-generated by tools/populate_inits.py\n", "__all__ = []\n"]

    for filename in os.listdir(directory):
        if filename == "__init__.py" or not filename.endswith(".py"):
            continue

        module_name = filename[:-3]
        file_path = os.path.join(directory, filename)
        callables = extract_callables(file_path)

        if callables:
            imports = f"from .{module_name} import {', '.join(callables)}\n"
            lines.append(imports)
            all_line = "__all__ += [{}]\n".format(", ".join(f'"{name}"' for name in callables))
            lines.append(all_line)

    if len(lines) > 2:
        with open(init_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
        print(f"Updated {init_path}")

def walk_and_populate(root):
    for dirpath, dirnames, filenames in os.walk(root):
        if "__init__.py" in filenames:
            populate_init_for_dir(dirpath)

# === Run script ===
if __name__ == "__main__":
    walk_and_populate(".")  # or "." if running from repo root