from microtorch.model_code.model_maker import ModelMaker
from microtorch.model_code.net_maker import Net

from microtorch.utils.acquisition_scheme import AquisitionScheme
from microtorch.utils.dataset import qMRIDataset
from microtorch.utils.preprocessing import PreProcess

from microtorch.train import train_single_scan_using_blocks
from microtorch.utils.args import gen_args


import torch
from gather_wand_data import load_wand

###file for training a model on multiple images!- under construction


mlp_activation = {'relu': torch.nn.ReLU(), 'prelu': torch.nn.PReLU(), 'tanh': torch.nn.Tanh(), 'elu': torch.nn.ELU()}



def fit_model_wand(
        image_paths, #These paths should be generated by gather_Wand_data.py if using wand
        mask_paths,
        args, #Remember args needs to be loaded with the correct parameters!!!
        device='cpu'  # Default device is CPU, can be changed to 'cuda' for GPU
):
    model_name = args.model #Get model name
    signal_model = ModelMaker(model_name) #


    grad_scheme = AquisitionScheme().load_scheme_from_args(args)
    pp = PreProcess(grad_scheme, signal_model.spherical_mean)
    dataset = qMRIDataset(image_paths, mask_paths, pp, grad_scheme)


    criterion = torch.nn.MSELoss()
    net = Net(grad_scheme, signal_model, dim_hidden=grad_scheme.number_of_measurements, num_layers=3,
              dropout_frac=args.dropout_frac, clipping_method=args.clip, activation=mlp_activation[args.activation])



    #Going to train model using quite a hacky way - iterating through dataset, then for each image, inputting into single train model
    #Typically with pytorch, i can just pop this dataset into a dataloader, but the model doesnt like this
    for i in range(dataset.__len__()):
        image = dataset.__getitem__(i)['image']
        _, __, net = train_single_scan_using_blocks(
            net,  # The model
            image,  # The data
            criterion,  # Loss function
            lr=args.learning_rate,  # Learning rate
            batch_size=256,  # Batch size
            epochs=args.num_iters,  # Number of iterations
            device=device  # Device to use (CPU or GPU)
        )


    torch.save(net.state_dict(), './results/wand_model.pth')

    return

def fit_model_single_image_test(image_path, mask_path, args):

    model_name = args.model
    signal_model = ModelMaker(model_name)

    grad_scheme = AquisitionScheme().load_scheme_from_args(args)

    i_paths = [image_path]
    m_paths = [mask_path]

    pp = PreProcess(grad_scheme, signal_model.spherical_mean)
    dataset = qMRIDataset(i_paths, m_paths, pp, grad_scheme)

    criterion = torch.nn.MSELoss()
    net = Net(grad_scheme, signal_model, dim_hidden=grad_scheme.number_of_measurements, num_layers=3, dropout_frac=args.dropout_frac, clipping_method=args.clip, activation=mlp_activation[args.activation])

    _, params = train_single_scan_using_blocks(net, dataset, criterion, lr=args.learning_rate, batch_size=256, epochs=args.num_iters)

    #batch_train(net, dataset, criterion, lr=args.learning_rate, batch_size=256, epochs=args.num_iters)




if __name__ == '__main__':

    path = r""
    images, masks, bvecs, bvals = load_wand(path)


    args = gen_args()
    args.bvals = bvals[0]
    args.bvecs = bvecs[0]
    args.model = "SANDI"

    fit_model_single_image_test(
        images,masks,args
    )

