defaults:
  - _self_
  - training: default
  - model: default
  - acquisition: default
  - data: default
  - tuning: default
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

plot:
  enabled: true
  zslice: 0
